version: 2.1
aliases:
  - &defaults
      docker:
        - image: circleci/openjdk:8-jdk
jobs:
    build_demo:
      <<: *defaults
      steps:
        - run:
            name: Cloning
            command: git clone https://github.com/maisamm77/demo.git principal
        - run:
            name: Saving HEAD checksum
            command: cd principal && echo "$(git rev-parse HEAD)" > /tmp/head_checksum
        - run:
            name: Building Demo
            command: |
              cd principal/;
                mvn clean package -DskipTests dependency:resolve-plugins dependency:go-offline
        - save_cache:
            name: "Caching dependencies"
            paths:
              - ~/.m2
            key: m2-demo-{{ checksum "principal/demo/pom.xml" }}
        - save_cache:
            name: "Caching JAR"
            paths:
              - ~/project/principal/demo/target
            key: art-v2-demo-{{ checksum "/tmp/head_checksum" }}
        - persist_to_workspace:
            root: principal/
            paths:
              - demo/pom.xml
              - demo/target/demo.jar

orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  build:
    jobs:
      - build_demo
