version: 2
aliases:
  - &defaults
      docker:
        - image: circleci/openjdk:8-jdk
jobs:
    build_demo:
      <<: *defaults
      steps:
        - checkout
        - run: pwd 
        - run:
            name: Saving HEAD checksum
            command: cd project && echo "$(git rev-parse HEAD)" > /tmp/head_checksum
        - restore_cache:
            name: "Retrieving cached dependencies"
            keys:
              - m2-demo-{{ checksum "project/pom.xml" }}
        - run:
            name: Building Demo
            command: |
              cd project/;
                mvn clean package -DskipTests dependency:resolve-plugins dependency:go-offline
        - save_cache:
            name: "Caching dependencies"
            paths:
              - ~/.m2
            key: m2-demo-{{ checksum "project/pom.xml" }}

orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  build:
    jobs:
      - build_demo
