version: 2.1
aliases:
  - &defaults
      docker:
        - image: circleci/openjdk:8-jdk
jobs:
    build_demo:
      <<: *defaults
      steps:
        - run:
            name: Cloning
            command: git clone https://github.com/maisamm77/demo.git principal
        - run:
            name: Saving HEAD checksum
            command: cd principal && echo "$(git rev-parse HEAD)" > /tmp/head_checksum
        - run:
            name: Building Demo
            command: |
              cd principal/;
                mvn clean package -DskipTests dependency:resolve-plugins dependency:go-offline

orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  build:
    jobs:
      - build_demo
